import React from 'react';
export const C = { GOLD: '#C9A84C', GOLD_LIGHT: '#E8D5A0', DARK: '#0A0B0D', DARK2: '#12141A', DARK3: '#1A1D26', GRAY: '#8A8F9E', WHITE: '#F0F0F0', GREEN: '#2ECC71', RED: '#E74C3C' };
export function InputField({ icon, label, type = 'text', value, onChange, onKeyDown, placeholder, extra }) {
  return (<div style={{ marginBottom: 20 }}><label style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 12, color: C.GOLD, textTransform: 'uppercase', letterSpacing: '1.5px', fontWeight: 600, display: 'block', marginBottom: 8 }}>{label}</label><div style={{ position: 'relative' }}><span style={{ position: 'absolute', left: 16, top: '50%', transform: 'translateY(-50%)', color: C.GRAY, fontSize: 15 }}>{icon}</span><input type={type} value={value} onChange={onChange} onKeyDown={onKeyDown} placeholder={placeholder} style={{ width: '100%', padding: '14px 16px 14px 44px', background: `${C.DARK}80`, border: `1px solid ${C.DARK3}`, borderRadius: 10, color: C.WHITE, fontSize: 15, fontFamily: "'DM Sans', sans-serif", outline: 'none', transition: 'border-color 0.3s', boxSizing: 'border-box' }} onFocus={e => e.target.style.borderColor = C.GOLD + '60'} onBlur={e => e.target.style.borderColor = C.DARK3} />{extra}</div></div>);
}
export function ErrorMsg({ msg }) { if (!msg) return null; return <div style={{ background: `${C.RED}12`, border: `1px solid ${C.RED}30`, borderRadius: 10, padding: '12px 16px', marginBottom: 20, fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: C.RED, display: 'flex', gap: 8, alignItems: 'center' }}><span>⚠</span>{msg}</div>; }
export function SuccessMsg({ msg }) { if (!msg) return null; return <div style={{ background: `${C.GREEN}12`, border: `1px solid ${C.GREEN}30`, borderRadius: 10, padding: '12px 16px', marginBottom: 20, fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: C.GREEN, display: 'flex', gap: 8, alignItems: 'center' }}><span>✓</span>{msg}</div>; }
export function Spinner() { return <span style={{ width: 18, height: 18, border: `2px solid ${C.DARK}40`, borderTopColor: C.DARK, borderRadius: '50%', animation: 'spin 0.8s linear infinite', display: 'inline-block' }} />; }
export function AuthBackground() { return (<><div style={{ position: 'absolute', inset: 0, background: `radial-gradient(ellipse 60% 50% at 50% 50%, ${C.GOLD}06 0%, transparent 60%), radial-gradient(circle at 15% 85%, ${C.GOLD}04 0%, transparent 35%), radial-gradient(circle at 85% 15%, ${C.GOLD}04 0%, transparent 35%)` }} /><div style={{ position: 'absolute', inset: 0, backgroundImage: `linear-gradient(${C.DARK3}30 1px, transparent 1px), linear-gradient(90deg, ${C.DARK3}30 1px, transparent 1px)`, backgroundSize: '60px 60px', opacity: 0.25 }} /></>); }
export function LogoHeader({ subtitle }) { return (<div style={{ textAlign: 'center', marginBottom: 36 }}><div style={{ width: 52, height: 52, background: `linear-gradient(135deg, ${C.GOLD}, #B8943F)`, borderRadius: 14, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Playfair Display', serif", fontWeight: 900, fontSize: 26, color: C.DARK, marginBottom: 14, boxShadow: `0 8px 32px ${C.GOLD}25` }}>A</div><h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 26, fontWeight: 700, color: C.WHITE }}>Aira<span style={{ color: C.GOLD }}>PropFirm</span></h1><p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: C.GRAY, marginTop: 6 }}>{subtitle}</p></div>); }
export function AuthCard({ children }) { return (<div style={{ background: `linear-gradient(160deg, ${C.DARK2}, ${C.DARK3})`, border: `1px solid ${C.GOLD}20`, borderRadius: 20, padding: '36px 32px', position: 'relative', overflow: 'hidden' }}><div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 2, background: `linear-gradient(90deg, transparent, ${C.GOLD}, transparent)` }} />{children}</div>); }
export function LinkBtn({ text, onClick }) { return <span onClick={onClick} style={{ color: C.GOLD, cursor: 'pointer', fontWeight: 600 }}>{text}</span>; }
export const goldBtnFull = { width: '100%', padding: 16, background: `linear-gradient(135deg, ${C.GOLD}, #B8943F)`, color: C.DARK, border: 'none', borderRadius: 10, fontSize: 15, fontWeight: 700, fontFamily: "'DM Sans', sans-serif", cursor: 'pointer', letterSpacing: '0.5px', textTransform: 'uppercase', boxShadow: `0 4px 20px ${C.GOLD}30`, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10 };
